### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by kmcoyle** [guru-yang/Meerkat#1]
I followed the instructions in Manual_0.189.pdf to install dependencies & compile the software from the github repo. I encountered an error when running `make`: this was fixed by adding `-lz `to the end of the first command following all.

For example:
```
bamreader: bamreader.o gzstream.o ReadGroup.o Histogram.o
	$(CXX) -L $(BTLIB) $(PROFILE) -o bamreader Histogram.o ReadGroup.o bamreader.o gzstream.o -lbamtools -lbamtools-utils **-lz**
```

Similarly for dre & sclus compiling.

**Comment by guru-yang** [comment]
Thank you for pointing this out. This is known to be caused by different versions of GCC.
